#apiVersion: v1
#kind: Service
#metadata:
#  name: myapp-service
#spec:
#  selector:
#    app: myapp
#  ports:
#  - port: 8080
#    protocol: TCP
#    targetPort: 8080
#
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: myapp-service
  namespace: myapp
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    app: myapp
<<<<<<< HEAD
=======
    namespace: myapp-other
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
>>>>>>> abf0f93c1759634718f2533dc024fc6d83f85f0d
